
service: quiz-server
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: production
  region: ap-northeast-1
  httpApi:
    cors: true

  iamRoleStatements:
    - Effect: Allow

      Action:
        - dynamodb:*
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/*

functions:
  postQuiz:
    handler: quiz.post_quiz
    environment:
      ENV: prodution
    events:
      - httpApi:
          path: /quiz
          method: post
  getQuiz:
    handler: quiz.get_quiz
    environment:
      ENV: prodution
    events:
      - httpApi:
          path: /quiz/{id}
          method: get
  getAllQuiz:
    handler: quiz.get_all_quiz
    environment:
      ENV: prodution
    events:
      - httpApi:
          path: /quiz
          method: get
  putQuiz:
    handler: quiz.put_quiz
    environment:
      ENV: prodution
    events:
      - httpApi:
          path: /quiz/{id}
          method: put
  deleteQuiz:
    handler: quiz.delete_quiz
    environment:
      ENV: prodution
    events:
      - httpApi:
          path: /quiz/{id}
          method: delete
  postAccess:
    handler: access.post_access
    environment:
      ENV: prodution
    events:
      - httpApi:
          path: /access
          method: post
  postInquery:
    handler: inquery.post_inquery
    environment:
      ENV: prodution
    events:
      - httpApi:
          path: /inquery
          method: post
  postQuizLike:
    handler: quizLike.post_like
    environment:
      stage: prodution
    events:
      - httpApi:
          path: /quizLike
          method: post
  deleteQuizLike:
    handler: quizLike.delete_like
    environment:
      stage: prodution
    events:
      - httpApi:
          path: /quizLike
          method: delete
  getQuizLike:
    handler: quizLike.get_like
    environment:
      stage: prodution
    events:
      - httpApi:
          path: /quizLike/{category}/{code}
          method: get
  getQuizLikeCount:
    handler: quizLike.get_like_count
    environment:
      stage: prodution
    events:
      - httpApi:
          path: /quizLikeCount/{category}/{code}
          method: get
  getQuizLikeByUidCount:
    handler: quizLike.get_like_count_by_uid
    environment:
      stage: prodution
    events:
      - httpApi:
          path: /quizLikeCountByUid/{category}/{code}/{uid}
          method: get


plugins:
  # 他のプラグイン
  - serverless-offline

resources:
 Resources:
   quizTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: QuizTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1 
   quizLike:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: QuizLike
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
   accessHistTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AccessHistTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1 
   inqueryHistTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: InqueryHistTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1 